checks:
  php: true
filter:
  excluded_paths:
    - tests/*
build:
  environment:
    php: 7.1.0
    pecl_extensions:
      - swoole
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run src/*
    my-tests:
      dependencies:
        before:
          - composer install
      tests:
        override:
          - composer test
