checks:
  php: true
filter:
  excluded_paths:
    - tests/*
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run src/*
    my-tests:
      environment:
        php:
          version: 7.1.0
          pecl_extensions:
            - swoole
      dependencies:
        before:
          - composer install
      tests:
        override:
          - composer test
